version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpma
    links:
      - db
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:80
  td_server:
    build: .
    container_name: tripledutch
    restart: unless-stopped
    ports: 
      - "8001:8001"
    depends_on:
      - phpma
    links:
      - db
    volumes:
      - ./logs:/logs
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-data:/var/cache/nginx
    links:
      - td_server
    restart: always
volumes:
  db:
    driver: local
  nginx-data: