version: "3"

services:
  dd_server:
    build: .
    ports: 
      - "8000:8000"
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=tda_live
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
    ports:
      - '6033:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  db:
    driver: local