version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: **** <-- do not put in version control 
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpma
    links:
      - db
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:8080
  td_server:
#    image: fryingdutch/resourcelock:latest
    build: .
    container_name: tripledutch
    restart: unless-stopped
    ports: 
      - "44300:44300"
    depends_on:
      - phpma
    links:
      - db
    volumes:
      - ./logs:/logs
      - ./ssl-certs:/ssl-certs
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-data:/var/cache/nginx
      - ./ssl-certs:/ssl-certs
    links:
      - td_server
    restart: always
volumes:
  db:
    driver: local
  nginx-data:
