env:
  RELEASES: /root/application/releases

on:
  push:
    branches:
      - 'master'

  # used to manually trigger build
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the docker image
      run: docker build . -t resourcelock --no-cache

  deploy:
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: scp files
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: .
          target: ${{ env.RELEASES }}/${{ github.run_number }}/

    - name: Set linkers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.RELEASES }} && 
          rm -f ../current && 
          ln -sf ${{ env.RELEASES }}/$(ls -tr | tail -n1) ../current &&
          cd ../current &&
          cp -r ../../shared/ssl-certs ssl-certs &&
          rm -f env.json &&
          cp -r ../../shared/env.json env.json &&
          rm -f nginx.conf &&
          cp -r ../../shared/nginx.conf nginx.conf &&
          rm -f docker-compose.yml &&
          ln -sf ../../shared/docker-compose.yml docker-compose.yml
        shell: bash
    - name: Run application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.RELEASES }}/../current &&
          docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_PASSWORD }} &&
          docker push fryingdutch/resourcelock:latest &&
          docker-compose -p resourcelock restart td_server
        shell: bash

    - name: Clean up deployments
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          if [[ $(($(ls -1 ${{ env.RELEASES }} | wc -l) - 5)) -gt 0 ]]; then
              cd ${{ env.RELEASES }} && ls -1t | tail -n $(($(ls -1 ${{ env.RELEASES }} | wc -l) - 5)) | xargs -r rm -rf
          fi
        shell: bash